# Generated by Django 6.0.3 on 2026-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_size", models.IntegerField(verbose_name="文件大小（字节）")),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "transcription",
                    models.TextField(
                        blank=True, null=True, verbose_name="语音识别结果"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="会议纪要"),
                ),
            ],
            options={
                "verbose_name": "音频记录",
                "verbose_name_plural": "音频记录",
            },
        ),
        migrations.CreateModel(
            name="Voiceprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="声纹名称"
                    ),
                ),
                ("feature", models.BinaryField(verbose_name="声纹特征（二进制存储）")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "声纹信息",
                "verbose_name_plural": "声纹信息",
            },
        ),
    ]
