# Generated by Django 6.0.3 on 2026-04-18 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceprint",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="voiceprint",
            name="name",
            field=models.CharField(max_length=100, verbose_name="声纹名称"),
        ),
        migrations.AlterUniqueTogether(
            name="voiceprint",
            unique_together={("user", "name")},
        ),
    ]
