# Generated by Django 6.0.3 on 2026-04-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0002_voiceprint_user_alter_voiceprint_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceprint",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="声纹文件路径"
            ),
        ),
    ]
