# Generated by Django 6.0.3 on 2026-04-20 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0003_voiceprint_file_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="模板名称")),
                ("system_prompt", models.TextField(verbose_name="系统提示词")),
                ("user_prompt", models.TextField(verbose_name="用户提示词")),
                (
                    "category",
                    models.CharField(
                        choices=[("default", "默认"), ("custom", "自定义")],
                        default="custom",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt模板",
                "verbose_name_plural": "Prompt模板",
            },
        ),
    ]
