# Generated by Django 6.0.3 on 2026-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0004_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="template_type",
            field=models.CharField(
                choices=[("summary", "纪要"), ("abstract", "摘要")],
                default="summary",
                max_length=20,
                verbose_name="模板类型",
            ),
        ),
    ]
