# Generated by Django 6.0.3 on 2026-04-21 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0005_prompt_template_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_index", models.IntegerField(verbose_name="段落序号")),
                ("start_time", models.FloatField(verbose_name="开始时间(秒)")),
                ("end_time", models.FloatField(verbose_name="结束时间(秒)")),
                ("title", models.CharField(max_length=100, verbose_name="段落小标题")),
                ("content", models.TextField(verbose_name="段落原文内容")),
                ("summary", models.TextField(verbose_name="段落核心总结")),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="是否用户手动编辑"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_segments",
                        to="asr_api.uploadedfile",
                        verbose_name="关联会议文件",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议分段",
                "verbose_name_plural": "会议分段列表",
                "ordering": ["segment_index"],
            },
        ),
    ]
