# Generated by Django 6.0.3 on 2026-04-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0006_meetingsegment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSummarySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("conclusion", "核心结论"),
                            ("content", "讨论内容"),
                            ("action_item", "待办事项"),
                        ],
                        max_length=50,
                        verbose_name="部分类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("start_time", models.FloatField(verbose_name="开始时间(秒)")),
                ("end_time", models.FloatField(verbose_name="结束时间(秒)")),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="是否用户手动编辑"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asr_api.meetingsummary",
                        verbose_name="关联会议纪要",
                    ),
                ),
            ],
            options={
                "verbose_name": "会议纪要部分",
                "verbose_name_plural": "会议纪要部分",
            },
        ),
    ]
