# Generated by Django 6.0.3 on 2026-04-28
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asr_api", "0007_meetingsummarysection"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="头像"
            ),
        ),
    ]
