# Generated by Django 6.0.3 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asr_api', '0008_add_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprint',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='voiceprint_avatars/', verbose_name='声纹头像'),
        ),
    ]
