# Generated by Django 6.0.3 on 2026-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0009_voiceprint_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="raw_sentence_info",
            field=models.JSONField(
                blank=True, null=True, verbose_name="原始句子数据（未合并）"
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="speaker_info",
            field=models.JSONField(
                blank=True, null=True, verbose_name="说话人信息（已合并优化）"
            ),
        ),
        migrations.DeleteModel(
            name="MeetingSummarySection",
        ),
    ]
