# Generated by Django 6.0.3 on 2026-04-30 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0010_transcription_raw_sentence_info_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voiceprint",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "声纹信息",
                "verbose_name_plural": "声纹信息",
            },
        ),
        migrations.AlterUniqueTogether(
            name="voiceprint",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="voiceprint",
            name="audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="voiceprint_audio/",
                verbose_name="声纹对应音频",
            ),
        ),
        migrations.AddField(
            model_name="voiceprint",
            name="source_meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="asr_api.uploadedfile",
                verbose_name="来源会议",
            ),
        ),
        migrations.AddField(
            model_name="voiceprint",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "手动注册"), ("auto", "会议自动采集")],
                default="manual",
                max_length=20,
                verbose_name="声纹来源",
            ),
        ),
        migrations.AlterField(
            model_name="voiceprint",
            name="file_path",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="声纹文件路径（旧字段，兼容用）",
            ),
        ),
        migrations.AlterField(
            model_name="voiceprint",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="声纹名称（旧字段，兼容用）",
            ),
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="说话人姓名")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="speaker_avatars/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "说话人",
                "verbose_name_plural": "说话人列表",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="voiceprint",
            name="speaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voiceprints",
                to="asr_api.speaker",
                verbose_name="所属说话人",
            ),
        ),
    ]
