# Generated by Django 6.0.3
# 阶段一：为 Transcription 模型添加统一的 segments 字段

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0011_alter_voiceprint_options_and_more"),
    ]

    operations = [
        # 新增 segments 字段，保持旧字段不变
        migrations.AddField(
            model_name="transcription",
            name="segments",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="句子分段数据（新）"
            ),
        ),
    ]

