# Generated by Django 6.0.3 on 2026-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asr_api", "0012_add_transcription_segments_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcription",
            name="raw_sentence_info",
        ),
        migrations.RemoveField(
            model_name="transcription",
            name="speaker_info",
        ),
        migrations.AlterField(
            model_name="transcription",
            name="segments",
            field=models.JSONField(blank=True, null=True, verbose_name="句子分段数据"),
        ),
    ]
